"""
Warning Event Model
Stores warning events generated by the edge warning system
Implements Feature 003 - Real-Time Warning System
"""
import json
from datetime import datetime
from typing import Optional, List
from sqlalchemy import Column, Integer, Float, String, Boolean, Index
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class WarningEvent(Base):
    """
    Warning event record

    Warning Types:
    - threshold: Absolute value exceeds configured threshold
    - rate: Rate of change exceeds historical average
    - predictive: Predicted value expected to exceed threshold
    - combined: Multiple indicators violating simultaneously

    Warning Levels:
    - NORMAL: All indicators within normal range
    - ATTENTION: Minor deviation, requires monitoring
    - WARNING: Significant deviation, requires action
    - ALARM: Critical deviation, immediate response needed
    """

    __tablename__ = "warning_events"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Warning Identification
    warning_id = Column(String(50), unique=True, nullable=False)
    warning_type = Column(String(20), nullable=False)
    warning_level = Column(String(20), nullable=False)

    # Context
    ring_number = Column(Integer, nullable=False)
    timestamp = Column(Float, nullable=False)

    # Indicator Information
    indicator_name = Column(String(50), nullable=False)
    indicator_value = Column(Float)
    indicator_unit = Column(String(20))

    # Threshold Information
    threshold_value = Column(Float)
    threshold_type = Column(String(20))

    # Rate Information
    rate_of_change = Column(Float)
    historical_average_rate = Column(Float)
    rate_multiplier = Column(Float)

    # Predictive Information
    predicted_value = Column(Float)
    prediction_confidence = Column(Float)
    prediction_horizon_hours = Column(Float)

    # Combined Warning Information
    combined_indicators = Column(String)  # JSON array

    # Status Tracking
    status = Column(String(20), default="active")
    acknowledged_at = Column(Float)
    acknowledged_by = Column(String(100))
    resolved_at = Column(Float)
    resolved_by = Column(String(100))
    resolution_notes = Column(String)

    # Notification Tracking
    notification_sent = Column(Boolean, default=False)
    notification_channels = Column(String)  # JSON array
    notification_timestamp = Column(Float)

    # Metadata
    created_at = Column(Float, default=lambda: datetime.utcnow().timestamp())
    updated_at = Column(Float, default=lambda: datetime.utcnow().timestamp())

    __table_args__ = (
        Index("idx_warning_events_ring", "ring_number"),
        Index("idx_warning_events_timestamp", "timestamp"),
        Index("idx_warning_events_status", "status"),
        Index("idx_warning_events_level", "warning_level"),
        Index("idx_warning_events_type", "warning_type"),
        Index("idx_warning_events_indicator", "indicator_name"),
        Index("idx_warning_events_status_level", "status", "warning_level"),
        Index("idx_warning_events_ring_timestamp", "ring_number", "timestamp"),
    )

    def get_combined_indicators(self) -> Optional[List[str]]:
        """Parse combined_indicators JSON to Python list"""
        if self.combined_indicators:
            return json.loads(self.combined_indicators)
        return None

    def set_combined_indicators(self, indicators: List[str]):
        """Serialize combined indicators to JSON"""
        self.combined_indicators = json.dumps(indicators)

    def get_notification_channels(self) -> Optional[List[str]]:
        """Parse notification_channels JSON to Python list"""
        if self.notification_channels:
            return json.loads(self.notification_channels)
        return None

    def set_notification_channels(self, channels: List[str]):
        """Serialize notification channels to JSON"""
        self.notification_channels = json.dumps(channels)

    def acknowledge(self, user_id: str):
        """Mark warning as acknowledged"""
        self.status = "acknowledged"
        self.acknowledged_at = datetime.utcnow().timestamp()
        self.acknowledged_by = user_id
        self.updated_at = datetime.utcnow().timestamp()

    def resolve(self, user_id: str, notes: Optional[str] = None):
        """Mark warning as resolved"""
        self.status = "resolved"
        self.resolved_at = datetime.utcnow().timestamp()
        self.resolved_by = user_id
        if notes:
            self.resolution_notes = notes
        self.updated_at = datetime.utcnow().timestamp()

    def mark_as_false_positive(self, user_id: str, notes: Optional[str] = None):
        """Mark warning as false positive"""
        self.status = "false_positive"
        self.resolved_at = datetime.utcnow().timestamp()
        self.resolved_by = user_id
        if notes:
            self.resolution_notes = notes
        self.updated_at = datetime.utcnow().timestamp()

    def to_dict(self) -> dict:
        """Convert to dictionary for API response"""
        return {
            "warning_id": self.warning_id,
            "warning_type": self.warning_type,
            "warning_level": self.warning_level,
            "ring_number": self.ring_number,
            "timestamp": self.timestamp,
            "indicator_name": self.indicator_name,
            "indicator_value": self.indicator_value,
            "indicator_unit": self.indicator_unit,
            "threshold_value": self.threshold_value,
            "status": self.status,
            "acknowledged_at": self.acknowledged_at,
            "acknowledged_by": self.acknowledged_by,
            "resolved_at": self.resolved_at,
            "resolved_by": self.resolved_by,
            "notification_sent": self.notification_sent,
            "notification_channels": self.get_notification_channels(),
            "combined_indicators": self.get_combined_indicators(),
        }
